# Databricks notebook source
# MAGIC %md
# MAGIC # Gold_Batch_Processing_Engine
# MAGIC
# MAGIC **Layer:** Gold
# MAGIC **Purpose:** Builds Gold layer aggregated tables from Silver data.
# MAGIC
# MAGIC **Source path:** `/Users/shivakumaryallanti5@gmail.com/project customer 360/Gold_Batch_Processing_Engine`

# COMMAND ----------

print("Gold Batch Processing Engine - building gold aggregations...")

# COMMAND ----------


{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {},
     "inputWidgets": {},
     "nuid": "6585ee63-193c-4785-be30-0b409d9a5e1e",
     "showTitle": true,
     "tableResultSettingsMap": {},
     "title": "Overview"
    }
   },
   "source": [
    "This notebook builds the Canada Life Customer 360 gold layer from silver sources.\n",
    "\n",
    "Gold outputs provide purpose-built business views (5 tables managed here; 6th table `pipeda_audit` maintained separately in [Compliance Audit Notebook](#notebook-2704371916535664)):\n",
    "\n",
    "* **customer_360**: Wide denormalised fact with 1 row/customer, current state, multi-source LEFT JOINs, cross-sell propensity signals\n",
    "* **regulatory_view**: Aggregate fact for OSFI B-10 reporting with gross/net face amounts and premiums by province and product\n",
    "* **ml_features**: Feature store with full SCD2 history for `lapse_count_lifetime` and `reinstatement_count`, no PII, `c360_customer_id` only\n",
    "* **book_of_business**: Fact with Unity Catalog RLS row filter on `advisor_id` — includes disability_gap_flag and ci_cross_sell_flag\n",
    "* **kpi_summary**: Daily KPIs aggregate including 30d churn rate using SCD2 `effective_date`\n",
    "\n",
    "All gold tables write to:\n",
    "* Unity Catalog: `dbw_c360_canadalife.gold.<table_name>` (single gold schema per project preferences)\n",
    "* ADLS Gen2: `abfss://gold@adlsc360canadalife.dfs.core.windows.net/gold/<table_name>/` (custom ADLS paths)\n",
    "\n",
    "Execution modes:\n",
    "* `PLAN` inspects configured targets without reading full outputs\n",
    "* `TEST` builds each target and previews rows without writing\n",
    "* `RUN` builds and writes gold outputs to Unity Catalog and ADLS\n",
    "\n",
    "Active runtime widgets:\n",
    "* `target_table_name`: choose one configured gold target to run, or use `ALL` to run the full gold pipeline (5 tables)\n",
    "* `run_date`: optional date filter for incremental gold refresh (defaults to current date)\n",
    "* `execution_mode`: controls whether the notebook plans, tests, or writes outputs\n",
    "* `optimize_output`: when `true`, runs `OPTIMIZE` on written gold Delta tables in `RUN` mode\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {},
     "inputWidgets": {},
     "nuid": "d2d9d35e-423f-4161-bced-8968128eedd4",
     "showTitle": true,
     "tableResultSettingsMap": {},
     "title": "Parameters and imports"
    }
   },
   "outputs": [],
   "source": [
    "# ==============================================================================\n",
    "# Notebook: Gold_Batch_Processing_Engine\n",
    "# Purpose   : Silver -> Gold business-ready outputs for Canada Life Customer 360\n",
    "#             with 5 gold tables (6th table pipeda_audit maintained separately)\n",
    "# Notes     :\n",
    "#             * All gold tables write to custom ADLS paths under gold container\n",
    "#             * Single gold schema consolidates all consumer-facing outputs\n",
    "#             * Default execution_mode is PLAN so the notebook is safe to run first\n",
    "# ==============================================================================\n",
    "import re\n",
    "import uuid\n",
    "from functools import reduce\n",
    "from datetime import datetime, timedelta\n",
    "\n",
    "from delta.tables import DeltaTable\n",
    "from pyspark.sql import functions as F\n",
    "from pyspark.sql import types as T\n",
    "from pyspark.sql.window import Window\n",
    "\n",
    "# ------------------------------------------------------------------------------\n",
    "# 1. Widget Parameters\n",
    "# ------------------------------------------------------------------------------\n",
    "for widget_name in [\n",
    "    \"target_table_name\",\n",
    "    \"run_date\",\n",
    "    \"execution_mode\",\n",
    "    \"optimize_output\",\n",
    "]:\n",
    "    try:\n",
    "        dbutils.widgets.remove(widget_name)\n",
    "    except Exception:\n",
    "        pass\n",
    "\n",
    "DEFAULT_CATALOG_NAME = \"dbw_c360_canadalife\"\n",
    "DEFAULT_SILVER_SCHEMA = \"silver\"\n",
    "DEFAULT_GOLD_SCHEMA = \"gold\"\n",
    "DEFAULT_GOLD_BASE_PATH = \"abfss://gold@adlsc360canadalife.dfs.core.windows.net/gold\"\n",
    "\n",
    "widget_defaults = {\n",
    "    \"target_table_name\": \"ALL\",\n",
    "    \"run_date\": \"\",\n",
    "    \"execution_mode\": \"PLAN\",   # PLAN | TEST | RUN\n",
    "    \"optimize_output\": \"false\",\n",
    "}\n",
    "\n",
    "for widget_name, default_value in widget_defaults.items():\n",
    "    dbutils.widgets.text(widget_name, default_value)\n",
    "\n",
    "catalog_name = DEFAULT_CATALOG_NAME\n",
    "silver_schema = DEFAULT_SILVER_SCHEMA\n",
    "gold_schema = DEFAULT_GOLD_SCHEMA\n",
    "target_table_name = dbutils.widgets.get(\"target_table_name\").strip() or \"ALL\"\n",
    "run_date = dbutils.widgets.get(\"run_date\").strip()\n",
    "gold_base_path = DEFAULT_GOLD_BASE_PATH\n",
    "execution_mode = (dbutils.widgets.get(\"execution_mode\").strip() or \"PLAN\").upper()\n",
    "optimize_output = dbutils.widgets.get(\"optimize_output\").strip().lower() == \"true\"\n",
    "run_id = str(uuid.uuid4())\n",
    "\n",
    "if execution_mode not in {\"PLAN\", \"TEST\", \"RUN\"}:\n",
    "    raise ValueError(\"execution_mode must be one of PLAN, TEST, or RUN\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {},
     "inputWidgets": {},
     "nuid": "510b1e29-4d0c-4856-af15-9930989d7504",
     "showTitle": true,
     "tableResultSettingsMap": {},
     "title": "Configuration summary"
    }
   },
   "source": [
    "This section centralizes notebook metadata:\n",
    "* silver source table mappings\n",
    "* target definitions and write modes\n",
    "* runtime caches for reusable datasets\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {},
     "inputWidgets": {},
     "nuid": "abb93d7b-bbc4-40bf-b057-6a1c349a04dc",
     "showTitle": true,
     "tableResultSettingsMap": {},
     "title": "Configuration and target metadata"
    }
   },
   "outputs": [],
   "source": [
    "# ------------------------------------------------------------------------------\n",
    "# 2. Constants and Configuration\n",
    "# ------------------------------------------------------------------------------\n",
    "SILVER_TABLES = {\n",
    "    \"customer.master\": \"customer_master\",\n",
    "    \"policy.individual_life_clean\": \"policy_individual_life_clean\",\n",
    "    \"policy.individual_life_enriched\": \"policy_individual_life_enriched\",\n",
    "    \"policy.disability_ci_clean\": \"policy_disability_ci_clean\",\n",
    "    \"policy.policy_rider_detail\": \"policy_policy_rider_detail\",\n",
    "    \"digital.portal_clean\": \"digital_portal_clean\",\n",
    "    \"interactions.callcentre_clean\": \"interactions_callcentre_clean\",\n",
    "    \"group_benefits.plan_clean\": \"group_benefits_plan_clean\",\n",
    "    \"group_benefits.certificate_clean\": \"group_benefits_certificate_clean\",\n",
    "    \"group_benefits.certificate_coverage_detail\": \"group_benefits_certificate_coverage_detail\",\n",
    "    \"freedom55.advisor_feed_clean\": \"freedom55_advisor_feed_clean\",\n",
    "    \"investments.climl_clean\": \"investments_climl_clean\",\n",
    "    \"investments.fund_allocation_detail\": \"investments_fund_allocation_detail\",\n",
    "    \"group_retirement.member_clean\": \"group_retirement_member_clean\",\n",
    "    \"reinsurance.treaty_clean\": \"reinsurance_treaty_clean\",\n",
    "    \"reference.product_code_mapping\": \"reference_product_code_mapping\",\n",
    "    \"reference.status_code_mapping\": \"reference_status_code_mapping\",\n",
    "    \"reference.rider_codes\": \"reference_rider_codes\",\n",
    "}\n",
    "\n",
    "# ------------------------------------------------------------------------------\n",
    "# Gold target configuration for the 5 business-ready outputs managed by this\n",
    "# notebook. The 6th output (pipeda_audit) is maintained separately in the\n",
    "# Compliance Audit Notebook (ID: 2704371916535664) and writes to the single\n",
    "# gold schema.\n",
    "# ------------------------------------------------------------------------------\n",
    "TARGET_CONFIG = {\n",
    "    \"customer_360\": {\n",
    "        \"kind\": \"business\",\n",
    "        \"sources\": [\n",
    "            \"customer.master\",\n",
    "            \"policy.individual_life_enriched\",\n",
    "            \"policy.disability_ci_clean\",\n",
    "            \"group_benefits.certificate_coverage_detail\",\n",
    "            \"group_retirement.member_clean\",\n",
    "            \"investments.climl_clean\",\n",
    "            \"interactions.callcentre_clean\",\n",
    "        ],\n",
    "        \"keys\": [\"customer_id\"],\n",
    "        \"write_mode\": \"overwrite\",\n",
    "        \"description\": \"Wide denormalised fact, 1 row/customer, current state with cross-sell propensity signals\",\n",
    "    },\n",
    "    \"regulatory_view\": {\n",
    "        \"kind\": \"business\",\n",
    "        \"sources\": [\n",
    "            \"policy.individual_life_enriched\",\n",
    "            \"reinsurance.treaty_clean\",\n",
    "        ],\n",
    "        \"keys\": [\"product_type_code_canonical\", \"province_clean\", \"policy_status_canonical\"],\n",
    "        \"write_mode\": \"overwrite\",\n",
    "        \"description\": \"Aggregate fact for OSFI B-10 reporting, gross/net face amounts and premiums by province\",\n",
    "    },\n",
    "    \"ml_features\": {\n",
    "        \"kind\": \"business\",\n",
    "        \"sources\": [\n",
    "            \"policy.individual_life_clean\",\n",
    "            \"digital.portal_clean\",\n",
    "            \"group_retirement.member_clean\",\n",
    "        ],\n",
    "        \"keys\": [\"customer_id\"],\n",
    "        \"write_mode\": \"overwrite\",\n",
    "        \"description\": \"Feature store with full SCD2 history for lapse_count_lifetime and reinstatement_count, no PII\",\n",
    "    },\n",
    "    \"book_of_business\": {\n",
    "        \"kind\": \"business\",\n",
    "        \"sources\": [\n",
    "            \"customer.master\",\n",
    "            \"freedom55.advisor_feed_clean\",\n",
    "            \"policy.individual_life_enriched\",\n",
    "        ],\n",
    "        \"keys\": [\"advisor_id\", \"customer_id\"],\n",
    "        \"write_mode\": \"overwrite\",\n",
    "        \"description\": \"Fact with Unity Catalog RLS row filter on advisor_id\",\n",
    "    },\n",
    "    \"kpi_summary\": {\n",
    "        \"kind\": \"business\",\n",
    "        \"sources\": [\n",
    "            \"policy.individual_life_clean\",\n",
    "        ],\n",
    "        \"keys\": [\"kpi_date\"],\n",
    "        \"write_mode\": \"overwrite\",\n",
    "        \"description\": \"Daily KPIs aggregate including 30d churn rate using SCD2 effective_date\",\n",
    "    },\n",
    "}\n",
    "\n",
    "TARGET_ORDER = [\n",
    "    \"customer_360\",\n",
    "    \"regulatory_view\",\n",
    "    \"ml_features\",\n",
    "    \"book_of_business\",\n",
    "    \"kpi_summary\",\n",
    "]\n",
    "\n",
    "DATAFRAME_CACHE = {}\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {},
     "inputWidgets": {},
     "nuid": "e9624939-1ba8-4dc9-9fca-c309321ffa08",
     "showTitle": true,
     "tableResultSettingsMap": {},
     "title": "Shared helpers"
    }
   },
   "source": [
    "These helper functions are reused across many targets.\n",
    "\n",
    "Highlights:\n",
    "* target and path name resolution\n",
    "* silver source reading with caching\n",
    "* Delta write helpers for custom ADLS paths\n",
    "* shared aggregation and window functions\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {},
     "inputWidgets": {},
     "nuid": "744ca399-b1e5-40a1-8ca2-11f30d682861",
     "showTitle": true,
     "tableResultSettingsMap": {},
     "title": "Utility functions"
    }
   },
   "outputs": [],
   "source": [
    "# ------------------------------------------------------------------------------\n",
    "# 3. Utility Functions\n",
    "# ------------------------------------------------------------------------------\n",
    "def logical_to_physical(name: str) -> str:\n",
    "    return re.sub(r\"[^a-zA-Z0-9]+\", \"_\", name.strip()).strip(\"_\").lower()\n",
    "\n",
    "\n",
    "def silver_table_fqn(source_name_value: str) -> str:\n",
    "    return f\"{catalog_name}.{silver_schema}.{SILVER_TABLES[source_name_value]}\"\n",
    "\n",
    "\n",
    "def gold_table_fqn(target_name_value: str) -> str:\n",
    "    return f\"{catalog_name}.{gold_schema}.{logical_to_physical(target_name_value)}\"\n",
    "\n",
    "\n",
    "def gold_storage_path(target_name_value: str) -> str:\n",
    "    return f\"{gold_base_path}/{logical_to_physical(target_name_value)}\"\n",
    "\n",
    "\n",
    "def table_exists(table_name: str) -> bool:\n",
    "    try:\n",
    "        return spark.catalog.tableExists(table_name)\n",
    "    except Exception:\n",
    "        return False\n",
    "\n",
    "\n",
    "def ensure_gold_schema() -> None:\n",
    "    spark.sql(f\"CREATE SCHEMA IF NOT EXISTS {catalog_name}.{gold_schema}\")\n",
    "\n",
    "\n",
    "def normalise_filter_value(name: str) -> str:\n",
    "    return logical_to_physical(name)\n",
    "\n",
    "\n",
    "def resolve_selected_targets() -> list:\n",
    "    if target_table_name.upper() != \"ALL\":\n",
    "        selected = [target_name for target_name in TARGET_ORDER if normalise_filter_value(target_name) == normalise_filter_value(target_table_name)]\n",
    "        if not selected:\n",
    "            raise ValueError(f\"Target '{target_table_name}' is not configured.\")\n",
    "        return selected\n",
    "    return TARGET_ORDER\n",
    "\n",
    "\n",
    "def read_silver_source(source_name_value: str):\n",
    "    if source_name_value in DATAFRAME_CACHE:\n",
    "        return DATAFRAME_CACHE[source_name_value]\n",
    "    df = spark.table(silver_table_fqn(source_name_value))\n",
    "    DATAFRAME_CACHE[source_name_value] = df\n",
    "    return df\n",
    "\n",
    "\n",
    "def ensure_external_table(target_name_value: str):\n",
    "    spark.sql(\n",
    "        f\"CREATE TABLE IF NOT EXISTS {gold_table_fqn(target_name_value)} USING DELTA LOCATION '{gold_storage_path(target_name_value)}'\"\n",
    "    )\n",
    "\n",
    "\n",
    "def write_delta(df, target_name_value: str, mode: str):\n",
    "    path = gold_storage_path(target_name_value)\n",
    "    projected_columns = []\n",
    "    seen_columns = set()\n",
    "    for column_name in df.columns:\n",
    "        if column_name not in seen_columns:\n",
    "            projected_columns.append(F.col(column_name).alias(column_name))\n",
    "            seen_columns.add(column_name)\n",
    "    output_df = df.select(*projected_columns)\n",
    "    if mode == \"append\":\n",
    "        output_df.write.format(\"delta\").mode(\"append\").option(\"mergeSchema\", \"true\").save(path)\n",
    "    else:\n",
    "        output_df.write.format(\"delta\").mode(\"overwrite\").option(\"overwriteSchema\", \"true\").save(path)\n",
    "    ensure_external_table(target_name_value)\n",
    "\n",
    "\n",
    "def maybe_optimize(target_name_value: str, zorder_columns: list):\n",
    "    if not optimize_output or execution_mode != \"RUN\":\n",
    "        return\n",
    "    valid_columns = [column_name for column_name in zorder_columns if column_name]\n",
    "    table_name = gold_table_fqn(target_name_value)\n",
    "    if valid_columns:\n",
    "        spark.sql(f\"OPTIMIZE {table_name} ZORDER BY ({', '.join(valid_columns)})\")\n",
    "    else:\n",
    "        spark.sql(f\"OPTIMIZE {table_name}\")\n",
    "\n",
    "\n",
    "def build_target_dataframe(target_name_value: str):\n",
    "    if target_name_value == \"customer_360\":\n",
    "        return build_customer_360()\n",
    "    elif target_name_value == \"regulatory_view\":\n",
    "        return build_regulatory_view()\n",
    "    elif target_name_value == \"ml_features\":\n",
    "        return build_ml_features()\n",
    "    elif target_name_value == \"book_of_business\":\n",
    "        return build_book_of_business()\n",
    "    elif target_name_value == \"kpi_summary\":\n",
    "        return build_kpi_summary()\n",
    "    else:\n",
    "        raise ValueError(f\"Unknown target: {target_name_value}\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {},
     "inputWidgets": {},
     "nuid": "250ba56d-2d32-4581-b0bd-9075b560c67b",
     "showTitle": true,
     "tableResultSettingsMap": {},
     "title": "Target builders and orchestration"
    }
   },
   "source": [
    "This section assembles silver sources into the final gold outputs.\n",
    "\n",
    "It includes:\n",
    "* business target builders for each gold table\n",
    "* the main execution loop for PLAN, TEST, and RUN\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {},
     "inputWidgets": {},
     "nuid": "067aba06-b3ca-4578-a6d0-1e964255e630",
     "showTitle": true,
     "tableResultSettingsMap": {},
     "title": "Target builders and execution"
    }
   },
   "outputs": [],
   "source": [
    "# ------------------------------------------------------------------------------\n",
    "# 4. Target Builders for Canada Life Customer 360 Gold Tables\n",
    "#\n",
    "# Five business-ready outputs (6th output, pipeda_audit, maintained separately\n",
    "# in Compliance Audit Notebook ID: 2704371916535664):\n",
    "#\n",
    "# G1: customer_360 - Wide denormalised fact, 1 row/customer, current state\n",
    "# G2: regulatory_view - Aggregate fact for OSFI B-10 compliance  \n",
    "# G3: ml_features - Feature store with full SCD2 history, no PII\n",
    "# G4: book_of_business - Fact with Unity Catalog RLS row filter on advisor_id\n",
    "# G5: kpi_summary - Daily KPIs aggregate\n",
    "# ------------------------------------------------------------------------------\n",
    "def build_customer_360():\n",
    "    \"\"\"\n",
    "    G1: Wide denormalised fact with 1 row/customer, current state, multi-source LEFT JOINs,\n",
    "    cross-sell propensity signals.\n",
    "    \"\"\"\n",
    "    customer_df = read_silver_source(\"customer.master\")\n",
    "    policy_enriched_df = read_silver_source(\"policy.individual_life_enriched\")\n",
    "    disability_df = read_silver_source(\"policy.disability_ci_clean\")\n",
    "    group_benefits_df = read_silver_source(\"group_benefits.certificate_coverage_detail\")\n",
    "    group_retirement_df = read_silver_source(\"group_retirement.member_clean\")\n",
    "    investments_df = read_silver_source(\"investments.climl_clean\")\n",
    "    callcentre_df = read_silver_source(\"interactions.callcentre_clean\")\n",
    "    \n",
    "    # Base: customer master\n",
    "    base_df = customer_df.select(\n",
    "        F.col(\"customer_id\"),\n",
    "        F.col(\"first_name\"),\n",
    "        F.col(\"last_name\"),\n",
    "        F.col(\"email_clean\"),\n",
    "        F.col(\"phone_clean\"),\n",
    "        F.col(\"province_clean\"),\n",
    "        F.col(\"postal_code_clean\"),\n",
    "        F.col(\"channel\"),\n",
    "        F.col(\"advisor_id\"),\n",
    "    )\n",
    "    \n",
    "    # Aggregate policy metrics using the live silver contract.\n",
    "    # `policy_status_canonical` is stored as compact codes (A, C, S, L, P), not words.\n",
    "    # Exclude terminal life statuses so current coverage metrics do not count lapsed/cancelled policies.\n",
    "    policy_current_df = policy_enriched_df.withColumn(\n",
    "        \"policy_status_canonical_normalized\",\n",
    "        F.upper(F.trim(F.coalesce(F.col(\"policy_status_canonical\"), F.lit(\"\"))))\n",
    "    ).filter(\n",
    "        ~F.col(\"policy_status_canonical_normalized\").isin(\"L\", \"C\")\n",
    "    )\n",
    "\n",
    "    policy_agg_df = policy_current_df.groupBy(\"customer_id\").agg(\n",
    "        F.count(\"*\").alias(\"life_policy_count\"),\n",
    "        F.sum(\"face_amount\").alias(\"total_life_face_amount\"),\n",
    "        F.sum(\"annualised_premium\").alias(\"total_life_premium\"),\n",
    "        F.max(F.col(\"term_expiring_90d_flag\").cast(\"int\")).alias(\"has_term_expiring_90d\"),\n",
    "        F.min(\"issue_date\").alias(\"first_policy_date\"),\n",
    "    )\n",
    "    \n",
    "    # Disability/CI coverage flags using current non-terminal records from the live silver contract.\n",
    "    disability_current_df = disability_df.withColumn(\n",
    "        \"policy_status_code_normalized\",\n",
    "        F.upper(F.trim(F.coalesce(F.col(\"policy_status_code\"), F.lit(\"\"))))\n",
    "    ).filter(\n",
    "        ~F.col(\"policy_status_code_normalized\").isin(\"LAPSED\", \"CANCELLED\")\n",
    "    )\n",
    "\n",
    "    disability_agg_df = disability_current_df.groupBy(\"customer_id\").agg(\n",
    "        F.when(\n",
    "            F.count(\"*\") > 0, F.lit(True)\n",
    "        ).otherwise(F.lit(False)).alias(\"has_disability_coverage\"),\n",
    "        F.when(\n",
    "            F.sum(F.when(F.col(\"product_type_code\").rlike(\"(?i)CI|CRITICAL\"), 1).otherwise(0)) > 0,\n",
    "            F.lit(True)\n",
    "        ).otherwise(F.lit(False)).alias(\"has_ci_coverage\"),\n",
    "    )\n",
    "    \n",
    "    # Group benefits: active members only\n",
    "    group_benefits_agg_df = group_benefits_df.filter(\n",
    "        F.col(\"termination_date\").isNull()\n",
    "    ).groupBy(\n",
    "        F.col(\"member_id\").alias(\"customer_id\")\n",
    "    ).agg(\n",
    "        F.countDistinct(\"plan_id\").alias(\"group_benefits_plan_count\"),\n",
    "    )\n",
    "    \n",
    "    # Group retirement: normalize live status values before current-state filtering.\n",
    "    group_retirement_agg_df = group_retirement_df.withColumn(\n",
    "        \"member_status_normalized\",\n",
    "        F.upper(F.trim(F.coalesce(F.col(\"member_status\"), F.lit(\"\"))))\n",
    "    ).filter(\n",
    "        F.col(\"member_status_normalized\") == \"ACTIVE\"\n",
    "    ).groupBy(\n",
    "        F.col(\"member_id\").alias(\"customer_id\")\n",
    "    ).agg(\n",
    "        F.sum(\"contribution_amount\").alias(\"total_retirement_contribution\"),\n",
    "    )\n",
    "    \n",
    "    # Investments\n",
    "    investments_agg_df = investments_df.groupBy(\"customer_id\").agg(\n",
    "        F.sum(\"market_value\").alias(\"total_investment_market_value\"),\n",
    "    )\n",
    "\n",
    "    # Join-key coverage note from live silver validation:\n",
    "    # policy_individual_life_enriched.customer_id overlaps with customer_master.customer_id,\n",
    "    # but the current group benefits, group retirement, investments, disability, and callcentre\n",
    "    # tables are on different identifier domains in the live data. Keep the LEFT JOIN structure\n",
    "    # intact for now so G1 remains runnable while Phase 1 continues toward contract alignment.\n",
    "    \n",
    "    # Call center: last interaction\n",
    "    callcentre_agg_df = callcentre_df.groupBy(\"customer_id\").agg(\n",
    "        F.max(\"call_start_ts\").alias(\"last_callcentre_contact\"),\n",
    "        F.count(\"*\").alias(\"callcentre_interaction_count\"),\n",
    "    )\n",
    "    \n",
    "    # LEFT JOINs\n",
    "    c360_df = base_df.join(\n",
    "        policy_agg_df, [\"customer_id\"], \"left\"\n",
    "    ).join(\n",
    "        disability_agg_df, [\"customer_id\"], \"left\"\n",
    "    ).join(\n",
    "        group_benefits_agg_df, [\"customer_id\"], \"left\"\n",
    "    ).join(\n",
    "        group_retirement_agg_df, [\"customer_id\"], \"left\"\n",
    "    ).join(\n",
    "        investments_agg_df, [\"customer_id\"], \"left\"\n",
    "    ).join(\n",
    "        callcentre_agg_df, [\"customer_id\"], \"left\"\n",
    "    )\n",
    "    \n",
    "    # Cross-sell propensity signals\n",
    "    c360_df = c360_df.withColumn(\n",
    "        \"cross_sell_propensity_ci\",\n",
    "        F.when(\n",
    "            (F.col(\"has_ci_coverage\").isNull() | (F.col(\"has_ci_coverage\") == False))\n",
    "            & (F.months_between(F.current_date(), F.col(\"first_policy_date\")) >= 6),\n",
    "            F.lit(True)\n",
    "        ).otherwise(F.lit(False))\n",
    "    ).withColumn(\n",
    "        \"cross_sell_term_conversion_flag\",\n",
    "        F.coalesce(F.col(\"has_term_expiring_90d\"), F.lit(0)).cast(\"boolean\")\n",
    "    )\n",
    "    \n",
    "    # Add gold metadata\n",
    "    result_df = c360_df.withColumn(\n",
    "        \"gold_ingested_at\", F.current_timestamp()\n",
    "    ).withColumn(\n",
    "        \"gold_run_id\", F.lit(run_id)\n",
    "    )\n",
    "    \n",
    "    return result_df\n",
    "\n",
    "\n",
    "def build_regulatory_view():\n",
    "    \"\"\"\n",
    "    G2: Aggregate fact for OSFI B-10 compliance, gross/net face amounts and premiums\n",
    "    by province and product.\n",
    "    \"\"\"\n",
    "    policy_enriched_df = read_silver_source(\"policy.individual_life_enriched\")\n",
    "    reinsurance_df = read_silver_source(\"reinsurance.treaty_clean\")\n",
    "    \n",
    "    # Policy aggregates using the live compact canonical status values.\n",
    "    policy_current_df = policy_enriched_df.withColumn(\n",
    "        \"policy_status_canonical_normalized\",\n",
    "        F.upper(F.trim(F.coalesce(F.col(\"policy_status_canonical\"), F.lit(\"\"))))\n",
    "    ).filter(\n",
    "        ~F.col(\"policy_status_canonical_normalized\").isin(\"L\", \"C\")\n",
    "    )\n",
    "\n",
    "    policy_agg_df = policy_current_df.groupBy(\n",
    "        F.col(\"product_type_code_canonical\"),\n",
    "        F.col(\"province_clean\"),\n",
    "        F.col(\"policy_status_canonical\"),\n",
    "    ).agg(\n",
    "        F.count(\"*\").alias(\"policy_count\"),\n",
    "        F.sum(\"face_amount\").alias(\"gross_face_amount\"),\n",
    "        F.sum(\"annualised_premium\").alias(\"gross_annualised_premium\"),\n",
    "        F.sum(\n",
    "            F.when(F.col(\"issue_date\") >= F.lit(\"2023-01-01\"), F.col(\"annualised_premium\")).otherwise(0)\n",
    "        ).alias(\"ifrs17_premium\"),\n",
    "    )\n",
    "    \n",
    "    # Reinsurance ceded amounts (join on policy_number, aggregate to same grain)\n",
    "    reinsurance_agg_df = reinsurance_df.groupBy(\n",
    "        F.col(\"policy_number\"),\n",
    "        F.col(\"product_type_code\"),\n",
    "        F.col(\"policy_status_code\"),\n",
    "    ).agg(\n",
    "        F.sum(\"ceded_amount\").alias(\"ceded_face_amount\"),\n",
    "        F.sum(\"premium_ceded\").alias(\"ceded_premium\"),\n",
    "    )\n",
    "    \n",
    "    # Join policy and reinsurance at policy level, then re-aggregate.\n",
    "    # Keep this on the same current-state life slice used in policy_agg_df.\n",
    "    policy_reinsurance_df = policy_current_df.join(\n",
    "        reinsurance_agg_df,\n",
    "        (policy_current_df[\"policy_number\"] == reinsurance_agg_df[\"policy_number\"])\n",
    "        & (policy_current_df[\"product_type_code\"] == reinsurance_agg_df[\"product_type_code\"]),\n",
    "        \"left\"\n",
    "    ).groupBy(\n",
    "        F.col(\"product_type_code_canonical\"),\n",
    "        F.col(\"province_clean\"),\n",
    "        F.col(\"policy_status_canonical\"),\n",
    "    ).agg(\n",
    "        F.sum(\"ceded_face_amount\").alias(\"total_ceded_face_amount\"),\n",
    "        F.sum(\"ceded_premium\").alias(\"total_ceded_premium\"),\n",
    "    )\n",
    "    \n",
    "    # Merge policy aggregates with ceded amounts\n",
    "    regulatory_df = policy_agg_df.join(\n",
    "        policy_reinsurance_df,\n",
    "        [\"product_type_code_canonical\", \"province_clean\", \"policy_status_canonical\"],\n",
    "        \"left\"\n",
    "    ).withColumn(\n",
    "        \"net_face_amount\",\n",
    "        F.col(\"gross_face_amount\") - F.coalesce(F.col(\"total_ceded_face_amount\"), F.lit(0))\n",
    "    ).withColumn(\n",
    "        \"net_annualised_premium\",\n",
    "        F.col(\"gross_annualised_premium\") - F.coalesce(F.col(\"total_ceded_premium\"), F.lit(0))\n",
    "    )\n",
    "    \n",
    "    # Add gold metadata\n",
    "    result_df = regulatory_df.withColumn(\n",
    "        \"gold_ingested_at\", F.current_timestamp()\n",
    "    ).withColumn(\n",
    "        \"gold_run_id\", F.lit(run_id)\n",
    "    )\n",
    "    \n",
    "    return result_df\n",
    "\n",
    "\n",
    "def build_ml_features():\n",
    "    \"\"\"\n",
    "    G3: Feature store with full SCD2 history for lapse_count_lifetime, reinstatement_count,\n",
    "    no PII, c360_customer_id only.\n",
    "    \"\"\"\n",
    "    policy_clean_df = read_silver_source(\"policy.individual_life_clean\")\n",
    "    digital_df = read_silver_source(\"digital.portal_clean\")\n",
    "    retirement_df = read_silver_source(\"group_retirement.member_clean\")\n",
    "    \n",
    "    # Policy features: use full SCD2 history (NO is_current filter), normalize status codes\n",
    "    # before lapse/reinstatement pattern detection.\n",
    "    policy_with_normalized_status = policy_clean_df.withColumn(\n",
    "        \"policy_status_normalized\",\n",
    "        F.upper(F.trim(F.coalesce(F.col(\"policy_status_code\"), F.lit(\"\"))))\n",
    "    )\n",
    "\n",
    "    policy_features_df = policy_with_normalized_status.groupBy(\"customer_id\").agg(\n",
    "        F.count(\"*\").alias(\"total_policy_history_count\"),\n",
    "        F.sum(\n",
    "            F.when(F.col(\"policy_status_normalized\").isin(\"L\", \"LAPSED\"), 1).otherwise(0)\n",
    "        ).alias(\"lapse_count_lifetime\"),\n",
    "        F.sum(\n",
    "            F.when(F.col(\"policy_status_normalized\").isin(\"R\", \"REINSTATED\"), 1).otherwise(0)\n",
    "        ).alias(\"reinstatement_count\"),\n",
    "        F.min(\"issue_date\").alias(\"first_policy_issue_date\"),\n",
    "    )\n",
    "    \n",
    "    # Digital engagement score (computed from event_type counts, no PII)\n",
    "    digital_features_df = digital_df.groupBy(\"customer_id\").agg(\n",
    "        F.sum(\n",
    "            F.when(F.col(\"event_type\") == \"login\", 1).otherwise(0)\n",
    "        ).alias(\"logins_count\"),\n",
    "        F.sum(\n",
    "            F.when(F.col(\"event_type\") == \"doc_download\", 1).otherwise(0)\n",
    "        ).alias(\"doc_downloads_count\"),\n",
    "        F.max(\"event_timestamp\").alias(\"last_digital_event_ts\"),\n",
    "    ).withColumn(\n",
    "        \"digital_engagement_score\",\n",
    "        (F.col(\"logins_count\") * 1.0) + (F.col(\"doc_downloads_count\") * 2.0)\n",
    "    )\n",
    "    \n",
    "    # Retirement participation (via member_id = customer_id), normalize status before active filter.\n",
    "    retirement_features_df = retirement_df.withColumn(\n",
    "        \"member_status_normalized\",\n",
    "        F.upper(F.trim(F.coalesce(F.col(\"member_status\"), F.lit(\"\"))))\n",
    "    ).filter(\n",
    "        F.col(\"member_status_normalized\") == \"ACTIVE\"\n",
    "    ).groupBy(\n",
    "        F.col(\"member_id\").alias(\"customer_id\")\n",
    "    ).agg(\n",
    "        F.sum(\"contribution_amount\").alias(\"total_retirement_contribution\"),\n",
    "        F.when(\n",
    "            F.sum(\"contribution_amount\") > 0, F.lit(True)\n",
    "        ).otherwise(F.lit(False)).alias(\"has_retirement_account\"),\n",
    "    )\n",
    "    \n",
    "    # Combine features\n",
    "    ml_features_df = policy_features_df.join(\n",
    "        digital_features_df, [\"customer_id\"], \"left\"\n",
    "    ).join(\n",
    "        retirement_features_df, [\"customer_id\"], \"left\"\n",
    "    )\n",
    "    \n",
    "    # Rename customer_id to c360_customer_id for ML context\n",
    "    result_df = ml_features_df.withColumnRenamed(\n",
    "        \"customer_id\", \"c360_customer_id\"\n",
    "    ).withColumn(\n",
    "        \"gold_ingested_at\", F.current_timestamp()\n",
    "    ).withColumn(\n",
    "        \"gold_run_id\", F.lit(run_id)\n",
    "    )\n",
    "    \n",
    "    return result_df\n",
    "\n",
    "\n",
    "def build_book_of_business():\n",
    "    \"\"\"\n",
    "    G4: Fact with Unity Catalog RLS row filter on advisor_id.\n",
    "    Includes disability_gap_flag and ci_cross_sell_flag.\n",
    "    \"\"\"\n",
    "    customer_df = read_silver_source(\"customer.master\")\n",
    "    advisor_df = read_silver_source(\"freedom55.advisor_feed_clean\")\n",
    "    policy_enriched_df = read_silver_source(\"policy.individual_life_enriched\")\n",
    "    \n",
    "    # Base: advisor assignments (active only)\n",
    "    advisor_base_df = advisor_df.filter(\n",
    "        (F.col(\"advisor_assignment_status\") == \"Active\")\n",
    "        | (F.col(\"assignment_end_date\").isNull())\n",
    "    ).select(\n",
    "        F.col(\"advisor_id\"),\n",
    "        F.col(\"customer_id\"),\n",
    "        F.col(\"assignment_start_date\"),\n",
    "        F.col(\"region\"),\n",
    "        F.col(\"channel\"),\n",
    "        F.col(\"policy_number\"),\n",
    "    )\n",
    "    \n",
    "    # Join customer details\n",
    "    book_df = advisor_base_df.join(\n",
    "        customer_df.select(\n",
    "            F.col(\"customer_id\"),\n",
    "            F.col(\"first_name\"),\n",
    "            F.col(\"last_name\"),\n",
    "            F.col(\"province_clean\"),\n",
    "        ),\n",
    "        [\"customer_id\"],\n",
    "        \"left\"\n",
    "    )\n",
    "    \n",
    "    # Join policy details using the live compact canonical status values.\n",
    "    policy_current_df = policy_enriched_df.withColumn(\n",
    "        \"policy_status_canonical_normalized\",\n",
    "        F.upper(F.trim(F.coalesce(F.col(\"policy_status_canonical\"), F.lit(\"\"))))\n",
    "    ).filter(\n",
    "        ~F.col(\"policy_status_canonical_normalized\").isin(\"L\", \"C\")\n",
    "    ).select(\n",
    "        F.col(\"customer_id\"),\n",
    "        F.col(\"policy_number\"),\n",
    "        F.col(\"product_type_code_canonical\"),\n",
    "        F.col(\"annualised_premium\"),\n",
    "        F.col(\"churn_risk_signal\"),\n",
    "        F.col(\"term_expiring_90d_flag\"),\n",
    "    )\n",
    "    \n",
    "    book_with_policy_df = book_df.join(\n",
    "        policy_current_df,\n",
    "        [\"customer_id\", \"policy_number\"],\n",
    "        \"left\"\n",
    "    )\n",
    "    \n",
    "    # Derived flags for cross-sell opportunities\n",
    "    book_with_flags_df = book_with_policy_df.withColumn(\n",
    "        \"disability_gap_flag\",\n",
    "        F.when(\n",
    "            ~F.col(\"product_type_code_canonical\").rlike(\"(?i)DI|DISABILITY\"),\n",
    "            F.lit(True)\n",
    "        ).otherwise(F.lit(False))\n",
    "    ).withColumn(\n",
    "        \"ci_cross_sell_flag\",\n",
    "        F.when(\n",
    "            ~F.col(\"product_type_code_canonical\").rlike(\"(?i)CI|CRITICAL\")\n",
    "            & (F.col(\"term_expiring_90d_flag\") == True),\n",
    "            F.lit(True)\n",
    "        ).otherwise(F.lit(False))\n",
    "    )\n",
    "    \n",
    "    # Add gold metadata\n",
    "    result_df = book_with_flags_df.withColumn(\n",
    "        \"gold_ingested_at\", F.current_timestamp()\n",
    "    ).withColumn(\n",
    "        \"gold_run_id\", F.lit(run_id)\n",
    "    )\n",
    "    \n",
    "    return result_df\n",
    "\n",
    "\n",
    "def build_kpi_summary():\n",
    "    \"\"\"\n",
    "    G5: Daily KPIs aggregate including 30d churn rate using SCD2 effective_date.\n",
    "    \"\"\"\n",
    "    policy_clean_df = read_silver_source(\"policy.individual_life_clean\")\n",
    "    policy_with_normalized_status = policy_clean_df.withColumn(\n",
    "        \"policy_status_normalized\",\n",
    "        F.upper(F.trim(F.coalesce(F.col(\"policy_status_code\"), F.lit(\"\"))))\n",
    "    )\n",
    "    \n",
    "    # Calculate 30-day churn rate using SCD2 effective_date and live status values.\n",
    "    churn_window_df = policy_with_normalized_status.filter(\n",
    "        F.col(\"effective_date\").isNotNull()\n",
    "    ).filter(\n",
    "        F.datediff(F.current_date(), F.col(\"effective_date\")).between(0, 30)\n",
    "    ).groupBy(\n",
    "        F.to_date(F.col(\"effective_date\")).alias(\"kpi_date\")\n",
    "    ).agg(\n",
    "        F.countDistinct(\"customer_id\").alias(\"active_customers\"),\n",
    "        F.sum(\n",
    "            F.when(F.col(\"policy_status_normalized\").isin(\"L\", \"LAPSED\", \"C\", \"CANCELLED\"), 1).otherwise(0)\n",
    "        ).alias(\"churned_customers\"),\n",
    "    ).withColumn(\n",
    "        \"churn_rate_30d\",\n",
    "        F.when(\n",
    "            F.col(\"active_customers\") > 0,\n",
    "            F.col(\"churned_customers\") / F.col(\"active_customers\")\n",
    "        ).otherwise(F.lit(0.0))\n",
    "    )\n",
    "    \n",
    "    # Other daily KPIs (policies issued, premiums written) on the live current-state slice.\n",
    "    daily_kpis_df = policy_with_normalized_status.filter(\n",
    "        F.col(\"policy_status_normalized\").isin(\"ACTIVE\", \"PENDING\", \"SUSPENDED\", \"A\", \"P\", \"S\")\n",
    "    ).filter(\n",
    "        F.col(\"issue_date\").isNotNull()\n",
    "    ).groupBy(\n",
    "        F.to_date(F.col(\"issue_date\")).alias(\"kpi_date\")\n",
    "    ).agg(\n",
    "        F.count(\"*\").alias(\"policies_issued\"),\n",
    "        F.sum(\"premium_amount\").alias(\"total_premium_written\"),\n",
    "        F.sum(\"face_amount\").alias(\"total_face_amount_issued\"),\n",
    "    )\n",
    "    \n",
    "    # Merge KPIs\n",
    "    kpi_df = churn_window_df.join(\n",
    "        daily_kpis_df, [\"kpi_date\"], \"outer\"\n",
    "    )\n",
    "    \n",
    "    # Add gold metadata\n",
    "    result_df = kpi_df.withColumn(\n",
    "        \"gold_ingested_at\", F.current_timestamp()\n",
    "    ).withColumn(\n",
    "        \"gold_run_id\", F.lit(run_id)\n",
    "    )\n",
    "    \n",
    "    return result_df\n",
    "\n",
    "\n",
    "# ------------------------------------------------------------------------------\n",
    "# 5. Execution Orchestration\n",
    "# ------------------------------------------------------------------------------\n",
    "ensure_gold_schema()\n",
    "selected_targets = resolve_selected_targets()\n",
    "result_rows = []\n",
    "\n",
    "print(f\"GOLD_EXECUTION_MODE={execution_mode}\")\n",
    "print(f\"GOLD_SELECTED_TARGETS={', '.join(selected_targets)}\")\n",
    "print(f\"GOLD_RUN_ID={run_id}\")\n",
    "print(f\"GOLD_RUN_DATE={run_date or 'FULL'}\")\n",
    "print(\"=\"*80)\n",
    "\n",
    "for target_name_value in selected_targets:\n",
    "    target_config = TARGET_CONFIG[target_name_value]\n",
    "    target_kind = target_config[\"kind\"]\n",
    "    target_write_mode = target_config[\"write_mode\"]\n",
    "    \n",
    "    print(f\"Processing target: {target_name_value} (kind={target_kind}, mode={target_write_mode})\")\n",
    "    \n",
    "    if execution_mode == \"PLAN\":\n",
    "        result_rows.append({\n",
    "            \"target_name\": target_name_value,\n",
    "            \"kind\": target_kind,\n",
    "            \"write_mode\": target_write_mode,\n",
    "            \"row_count\": None,\n",
    "            \"target_table\": gold_table_fqn(target_name_value),\n",
    "            \"target_path\": gold_storage_path(target_name_value),\n",
    "            \"status\": \"PLANNED\",\n",
    "            \"message\": \"Execution skipped in PLAN mode\",\n",
    "        })\n",
    "    else:\n",
    "        try:\n",
    "            target_df = build_target_dataframe(target_name_value)\n",
    "            target_count = target_df.count()\n",
    "            \n",
    "            if execution_mode == \"TEST\":\n",
    "                print(f\"  Row count: {target_count}\")\n",
    "                preview_df = target_df.limit(5)\n",
    "                display(preview_df)\n",
    "                result_rows.append({\n",
    "                    \"target_name\": target_name_value,\n",
    "                    \"kind\": target_kind,\n",
    "                    \"write_mode\": target_write_mode,\n",
    "                    \"row_count\": target_count,\n",
    "                    \"target_table\": gold_table_fqn(target_name_value),\n",
    "                    \"target_path\": gold_storage_path(target_name_value),\n",
    "                    \"status\": \"TESTED\",\n",
    "                    \"message\": f\"Preview generated with {target_count} rows\",\n",
    "                })\n",
    "            elif execution_mode == \"RUN\":\n",
    "                write_delta(target_df, target_name_value, target_write_mode)\n",
    "                maybe_optimize(target_name_value, target_config[\"keys\"])\n",
    "                print(f\"  Written {target_count} rows to {gold_table_fqn(target_name_value)}\")\n",
    "                result_rows.append({\n",
    "                    \"target_name\": target_name_value,\n",
    "                    \"kind\": target_kind,\n",
    "                    \"write_mode\": target_write_mode,\n",
    "                    \"row_count\": target_count,\n",
    "                    \"target_table\": gold_table_fqn(target_name_value),\n",
    "                    \"target_path\": gold_storage_path(target_name_value),\n",
    "                    \"status\": \"SUCCESS\",\n",
    "                    \"message\": f\"Successfully written {target_count} rows\",\n",
    "                })\n",
    "        except Exception as exc:\n",
    "            import traceback\n",
    "            error_message = f\"{type(exc).__name__}: {str(exc)}\"\n",
    "            print(f\"  FAILED: {error_message}\")\n",
    "            traceback.print_exc(limit=10)\n",
    "            result_rows.append({\n",
    "                \"target_name\": target_name_value,\n",
    "                \"kind\": target_kind,\n",
    "                \"write_mode\": target_write_mode,\n",
    "                \"row_count\": None,\n",
    "                \"target_table\": gold_table_fqn(target_name_value),\n",
    "                \"target_path\": gold_storage_path(target_name_value),\n",
    "                \"status\": \"FAILED\",\n",
    "                \"message\": error_message,\n",
    "            })\n",
    "\n",
    "print(\"=\"*80)\n",
    "print(f\"GOLD_EXECUTION_COMPLETE|mode={execution_mode}|targets={len(selected_targets)}\")\n",
    "\n",
    "result_schema = T.StructType([\n",
    "    T.StructField(\"target_name\", T.StringType(), True),\n",
    "    T.StructField(\"kind\", T.StringType(), True),\n",
    "    T.StructField(\"write_mode\", T.StringType(), True),\n",
    "    T.StructField(\"row_count\", T.LongType(), True),\n",
    "    T.StructField(\"target_table\", T.StringType(), True),\n",
    "    T.StructField(\"target_path\", T.StringType(), True),\n",
    "    T.StructField(\"status\", T.StringType(), True),\n",
    "    T.StructField(\"message\", T.StringType(), True),\n",
    "])\n",
    "result_df = spark.createDataFrame(result_rows, result_schema)\n",
    "display(result_df)\n",
    "\n",
    "failed_rows = [row for row in result_rows if row.get(\"status\") == \"FAILED\"]\n",
    "if failed_rows:\n",
    "    print(\"FAILED_TARGET_SUMMARY_START\")\n",
    "    for failed_row in failed_rows:\n",
    "        print(\n",
    "            f\"FAILED_TARGET|{failed_row['target_name']}|{failed_row['write_mode']}|{failed_row['message']}\"\n",
    "        )\n",
    "    print(\"FAILED_TARGET_SUMMARY_END\")\n",
    "    failed_target_names = \", \".join(row[\"target_name\"] for row in failed_rows)\n",
    "    print(f\"FAILED_TARGET_NAMES={failed_target_names}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {},
     "inputWidgets": {},
     "nuid": "40345b76-0a30-46b9-8f9a-986cad1708f1",
     "showTitle": true,
     "tableResultSettingsMap": {},
     "title": "Gold validation checks"
    }
   },
   "outputs": [],
   "source": [
    "# ------------------------------------------------------------------------------\n",
    "# 6. Gold Validation Checks\n",
    "# ------------------------------------------------------------------------------\n",
    "if execution_mode != \"RUN\":\n",
    "    print(f\"Gold validation skipped in {execution_mode} mode.\")\n",
    "else:\n",
    "    validation_results = []\n",
    "    \n",
    "    # Check 1: All 5 gold tables exist\n",
    "    all_gold_tables_exist = all(\n",
    "        table_exists(gold_table_fqn(target_name))\n",
    "        for target_name in TARGET_ORDER\n",
    "    )\n",
    "    validation_results.append({\"check_name\": \"all_5_tables_present\", \"passed\": all_gold_tables_exist})\n",
    "    \n",
    "    # Check 2: customer_360 has expected columns and rows\n",
    "    if table_exists(gold_table_fqn(\"customer_360\")):\n",
    "        customer_360_df = spark.table(gold_table_fqn(\"customer_360\"))\n",
    "        expected_c360_cols = {\"customer_id\", \"first_name\", \"last_name\", \"email_clean\", \"phone_clean\"}\n",
    "        has_c360_cols = expected_c360_cols.issubset(set(customer_360_df.columns))\n",
    "        validation_results.append({\"check_name\": \"customer_360_has_expected_cols\", \"passed\": has_c360_cols})\n",
    "        \n",
    "        customer_count = customer_360_df.count()\n",
    "        validation_results.append({\"check_name\": \"customer_360_populated\", \"passed\": customer_count > 0})\n",
    "    else:\n",
    "        validation_results.append({\"check_name\": \"customer_360_has_expected_cols\", \"passed\": False})\n",
    "        validation_results.append({\"check_name\": \"customer_360_populated\", \"passed\": False})\n",
    "    \n",
    "    # Check 3: regulatory_view has expected columns\n",
    "    if table_exists(gold_table_fqn(\"regulatory_view\")):\n",
    "        regulatory_df = spark.table(gold_table_fqn(\"regulatory_view\"))\n",
    "        expected_regulatory_cols = {\"product_type_code_canonical\", \"province_clean\", \"gross_face_amount\", \"net_face_amount\"}\n",
    "        has_regulatory_cols = expected_regulatory_cols.issubset(set(regulatory_df.columns))\n",
    "        validation_results.append({\"check_name\": \"regulatory_view_has_expected_cols\", \"passed\": has_regulatory_cols})\n",
    "        \n",
    "        regulatory_count = regulatory_df.count()\n",
    "        validation_results.append({\"check_name\": \"regulatory_view_populated\", \"passed\": regulatory_count > 0})\n",
    "    else:\n",
    "        validation_results.append({\"check_name\": \"regulatory_view_has_expected_cols\", \"passed\": False})\n",
    "        validation_results.append({\"check_name\": \"regulatory_view_populated\", \"passed\": False})\n",
    "    \n",
    "    # Check 4: ml_features has c360_customer_id, lapse_count_lifetime, reinstatement_count\n",
    "    if table_exists(gold_table_fqn(\"ml_features\")):\n",
    "        ml_features_df = spark.table(gold_table_fqn(\"ml_features\"))\n",
    "        expected_ml_cols = {\"c360_customer_id\", \"lapse_count_lifetime\", \"reinstatement_count\"}\n",
    "        has_ml_cols = expected_ml_cols.issubset(set(ml_features_df.columns))\n",
    "        validation_results.append({\"check_name\": \"ml_features_has_expected_cols\", \"passed\": has_ml_cols})\n",
    "        \n",
    "        ml_count = ml_features_df.count()\n",
    "        validation_results.append({\"check_name\": \"ml_features_populated\", \"passed\": ml_count > 0})\n",
    "    else:\n",
    "        validation_results.append({\"check_name\": \"ml_features_has_expected_cols\", \"passed\": False})\n",
    "        validation_results.append({\"check_name\": \"ml_features_populated\", \"passed\": False})\n",
    "    \n",
    "    # Check 5: book_of_business has advisor_id and cross-sell flags\n",
    "    if table_exists(gold_table_fqn(\"book_of_business\")):\n",
    "        book_df = spark.table(gold_table_fqn(\"book_of_business\"))\n",
    "        expected_book_cols = {\"advisor_id\", \"customer_id\", \"disability_gap_flag\", \"ci_cross_sell_flag\"}\n",
    "        has_book_cols = expected_book_cols.issubset(set(book_df.columns))\n",
    "        validation_results.append({\"check_name\": \"book_of_business_has_expected_cols\", \"passed\": has_book_cols})\n",
    "        \n",
    "        book_count = book_df.count()\n",
    "        validation_results.append({\"check_name\": \"book_of_business_populated\", \"passed\": book_count > 0})\n",
    "    else:\n",
    "        validation_results.append({\"check_name\": \"book_of_business_has_expected_cols\", \"passed\": False})\n",
    "        validation_results.append({\"check_name\": \"book_of_business_populated\", \"passed\": False})\n",
    "    \n",
    "    # Check 6: kpi_summary has kpi_date and churn_rate_30d\n",
    "    if table_exists(gold_table_fqn(\"kpi_summary\")):\n",
    "        kpi_df = spark.table(gold_table_fqn(\"kpi_summary\"))\n",
    "        expected_kpi_cols = {\"kpi_date\", \"churn_rate_30d\"}\n",
    "        has_kpi_cols = expected_kpi_cols.issubset(set(kpi_df.columns))\n",
    "        validation_results.append({\"check_name\": \"kpi_summary_has_expected_cols\", \"passed\": has_kpi_cols})\n",
    "        \n",
    "        kpi_count = kpi_df.count()\n",
    "        validation_results.append({\"check_name\": \"kpi_summary_populated\", \"passed\": kpi_count > 0})\n",
    "    else:\n",
    "        validation_results.append({\"check_name\": \"kpi_summary_has_expected_cols\", \"passed\": False})\n",
    "        validation_results.append({\"check_name\": \"kpi_summary_populated\", \"passed\": False})\n",
    "    \n",
    "    # Check 7: All gold tables have gold_run_id and gold_ingested_at\n",
    "    all_have_gold_metadata = True\n",
    "    for target_name in TARGET_ORDER:\n",
    "        if table_exists(gold_table_fqn(target_name)):\n",
    "            table_df = spark.table(gold_table_fqn(target_name))\n",
    "            table_cols = set(table_df.columns)\n",
    "            if \"gold_run_id\" not in table_cols or \"gold_ingested_at\" not in table_cols:\n",
    "                all_have_gold_metadata = False\n",
    "                break\n",
    "        else:\n",
    "            all_have_gold_metadata = False\n",
    "            break\n",
    "    validation_results.append({\"check_name\": \"all_tables_have_gold_metadata\", \"passed\": all_have_gold_metadata})\n",
    "    \n",
    "    # Display validation results\n",
    "    validation_schema = T.StructType([\n",
    "        T.StructField(\"check_name\", T.StringType(), True),\n",
    "        T.StructField(\"passed\", T.BooleanType(), True),\n",
    "    ])\n",
    "    validation_df = spark.createDataFrame(validation_results, validation_schema)\n",
    "    display(validation_df)\n",
    "    \n",
    "    # Summary\n",
    "    failed_checks = [check for check in validation_results if not check[\"passed\"]]\n",
    "    if failed_checks:\n",
    "        failed_check_names = \", \".join(check[\"check_name\"] for check in failed_checks)\n",
    "        print(f\"FAILED_VALIDATION_CHECKS={failed_check_names}\")\n",
    "        print(\"GOLD_EXPECTATION_STATUS=FAIL\")\n",
    "    else:\n",
    "        print(\"FAILED_VALIDATION_CHECKS=NONE\")\n",
    "        print(\"GOLD_EXPECTATION_STATUS=PASS\")\n",
    "    \n",
    "    # Sample from each gold table\n",
    "    sample_results = []\n",
    "    for target_name in TARGET_ORDER:\n",
    "        if table_exists(gold_table_fqn(target_name)):\n",
    "            table_df = spark.table(gold_table_fqn(target_name))\n",
    "            sample_row = table_df.limit(1).collect()\n",
    "            if sample_row:\n",
    "                sample_results.append({\n",
    "                    \"table_name\": target_name,\n",
    "                    \"sample_value\": str(sample_row[0].asDict()),\n",
    "                })\n",
    "    \n",
    "    if sample_results:\n",
    "        sample_schema = T.StructType([\n",
    "            T.StructField(\"table_name\", T.StringType(), True),\n",
    "            T.StructField(\"sample_value\", T.StringType(), True),\n",
    "        ])\n",
    "        sample_df = spark.createDataFrame(sample_results, sample_schema)\n",
    "        display(sample_df)\n"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": null,
   "inputWidgetPreferences": null,
   "language": "python",
   "notebookMetadata": {},
   "notebookName": "Gold_Batch_Processing_Engine",
   "widgets": {}
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
